import type { ReactNode } from "react";

export const metadata = {
  title: "Terms of Service — Agent Marketing Autopilot",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <SiteHeader />

      <section className="mx-auto max-w-3xl px-6 py-16">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-silver-dark">
          Last updated: June 5, 2026
        </p>
        <h1 className="mt-3 font-serif text-4xl font-bold tracking-tight text-navy">
          Terms of Service
        </h1>

        <div className="mt-10 space-y-10">
          <Section title="1. Acceptance of Terms">
            By using Agent Marketing Autopilot, you agree to these terms.
          </Section>

          <Section title="2. Service Description">
            Agent Marketing Autopilot is a software-as-a-service product that
            uses AI to help residential real estate agents generate marketing
            content including listing descriptions, social media posts, and
            follow-up email sequences.
          </Section>

          <Section title="3. Subscription and Billing">
            The service is offered on a subscription basis with a 14-day free
            trial. After the trial, your card on file will be charged the
            then-current subscription price monthly. You can cancel at any time
            through the Stripe Customer Portal. Cancellation takes effect
            immediately and you lose access to the service.
          </Section>

          <Section title="4. Acceptable Use">
            You may use the service for legitimate real estate marketing
            purposes. You may not use it to generate illegal, deceptive, or
            harmful content, or attempt to abuse, exploit, or reverse-engineer
            the service.
          </Section>

          <Section title="5. Content Ownership">
            You retain ownership of all inputs you provide and outputs generated
            for your use. We do not claim ownership over your generated content.
          </Section>

          <Section title="6. AI-Generated Content Disclaimer">
            Output is generated by AI and should be reviewed for accuracy before
            publishing. We are not responsible for any consequences arising from
            your use of generated content, including but not limited to MLS
            violations, regulatory issues, or factual inaccuracies in listing
            descriptions.
          </Section>

          <Section title="7. Limitation of Liability">
            The service is provided &quot;as is&quot; without warranty. We are
            not liable for any indirect, incidental, or consequential damages
            arising from your use of the service.
          </Section>

          <Section title="8. Changes to Terms">
            We may update these terms from time to time. Continued use of the
            service after changes constitutes acceptance of the new terms.
          </Section>

          <Section title="9. Contact">
            For questions about these terms, contact brianwielhouwer@gmail.com.
          </Section>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div>
      <h2 className="font-serif text-xl font-bold text-navy">{title}</h2>
      <p className="mt-3 text-base leading-relaxed text-silver-dark">
        {children}
      </p>
    </div>
  );
}

function SiteHeader() {
  return (
    <header className="bg-navy">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
        <a href="/" className="flex items-center gap-3">
          <img
            src="/logo.png"
            alt="Compass Line Ventures"
            className="h-10 w-auto"
          />
        </a>
        <span className="text-[11px] font-semibold uppercase tracking-[0.25em] text-silver">
          Agent Marketing Autopilot
        </span>
      </div>
    </header>
  );
}

function SiteFooter() {
  return (
    <footer className="bg-navy text-white">
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-4 px-6 py-10 sm:flex-row sm:justify-between">
        <div className="flex items-center gap-3">
          <img
            src="/logo.png"
            alt="Compass Line Ventures"
            className="h-9 w-auto"
          />
        </div>
        <div className="text-center text-xs text-silver sm:text-right">
          <div className="font-semibold uppercase tracking-[0.2em] text-white">
            Compass Line Ventures
          </div>
          <div className="mt-1">
            &copy; {new Date().getFullYear()} All rights reserved.
          </div>
          <div className="mt-2 flex justify-center gap-4 sm:justify-end">
            <a href="/privacy" className="hover:text-white">
              Privacy
            </a>
            <a href="/terms" className="hover:text-white">
              Terms
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
